name: Cypress Docker Push
on: 
  push: 
    branches: [ "main" ]
  
jobs:
  Cypress-Test:
   
    name: Build Docker Image
    runs-on: self-hosted 
    steps:  
        - name: Checkout
          uses: actions/checkout@v2    
          
        - name: Build and push the tagged docker image to Amazon ECR
          env:
            ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}
            IMAGE_TAG: latest
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


            
       
  
